site_name: 'Progress'
site_url: 'http://progress.mplatvoet.nl'
site_description: 'Progress documentation. Track progress for Kotlin.'
site_author: 'Mark Platvoet'
copyright: '2015'

repo_url: https://github.com/mplatvoet/progress
repo_name: 'GitHub'

pages:
- ['index.md', 'Home']

theme_dir: theme/yeti